### ISSUE TITLE
[Bug]: Uncaught TypeError: setting getter-only property "attributeName"

### ISSUE THREAD

**Issue by njindal1501** [rrweb-io/rrweb#1194]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

rrweb@2.0.0-alpha.5

### Expected Behavior

This issue should not be thrown.

### Actual Behavior

Receiving this error again and again for iframe.

### Steps to Reproduce

I am getting this issue when opened a file in iframe. 
When debugged the issue, I found that this issue was coming from the below code snippet in 'rrweb/src/record/mutation.ts:516'
"" if (
          target.tagName === 'IFRAME' &&
          m.attributeName === 'src' &&
          !this.keepIframeSrcFn(value as string)
        ) {
          if (!(target as HTMLIFrameElement).contentDocument) {
            // we can't record it directly as we can't see into it
            // preserve the src attribute so a decision can be taken at replay time
            m.attributeName = 'rr_src';
          } else {
            return;
          }
        } ""

**Comment by njindal1501** [comment]
This is already fixed and merged.

**Comment by 2513483494** [comment]
<script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/record/rrweb-record.min.js"></script>

still get this error.@njindal1501

**Comment by 2513483494** [comment]
How can I fix this bug?
<script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/record/rrweb-record.min.js"></script>

**Comment by wfk007** [comment]
> How can I fix this bug?
> 
> <script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/record/rrweb-record.min.js"></script>

@2513483494 you can try the version 2.0.0-alpha.8，https://github.com/rrweb-io/rrweb/pull/1173 this PR has fixed this error

```
<script src="https://cdn.jsdelivr.net/npm/rrweb@2.0.0-alpha.8/dist/record/rrweb-record.min.js"></script>
```
