### ISSUE TITLE
[Bug]: Using RRWeb in chrome extension results in obfuscated code

### ISSUE THREAD

**Issue by nuwansamaware** [rrweb-io/rrweb#1578]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.14

### Expected Behavior

I am using rrweb in my chrome extension, and I am not using any minification compiling my extension. However, the output js contains following coming from rrweb usage: 
const encodedJs = "KGZ1bmN0aW9uKCkgewogICJ1c2Ugc3RyaWN0IjsKIC

This is causing chrome web store to reject my extension - which says there cannot be obfuscated code. Any idea how I can resolve this and use rrweb in my extension.

I have attached the decoded version of the code that the above encodedJs refers to.
[decoded_bitmap.txt](https://github.com/user-attachments/files/17218603/decoded_bitmap.txt)

### Actual Behavior

When compiled, not to have obfuscated portions of code.

### Steps to Reproduce

Include rrweb in extension. 
Compile. 
Check the output code

**Comment by pauldambra** [comment]
+1 numerous reports of this from folk too
we spoke to google dev rel, and it's not a thing they can/will ignore

**Comment by ebloom19** [comment]
Hey guys I am not sure if this helps at all but I also use Sentry in my Chrome Extension and their "Replay" feature (which also uses the rrweb package) seems to work fine in my extension without google flagging it for obfuscated code.

They seem to be using their own forked version I think?

Check out the packages they use:
https://github.com/getsentry/sentry/blob/ef56dcdb29f0ec074fc68acc865cf168c5d043af/package.json#L57

This is the rrweb npm package they seem to be using:
`@sentry-internal/rrweb`
https://www.npmjs.com/package/@sentry-internal/rrweb

Possibly there could be something there that may help with Posthog's solution?

**Comment by pauldambra** [comment]
Hey @ebloom19,

Sentry by default don't include the canvas recording code in their forked build. My guess is that if you included the Sentry canvas recording integration and used Sentry's replay then Google would block that too - assuming they're including the same "obfuscated" rrweb code when canvas replay is enabled

**Comment by seawatts** [comment]
@pauldambra thanks for looking into this and contacting Google. Is there anyway the code would be able to be changed in order for this to get published? Or is there a way to just exclude part of the posthog lib for chrome extensions?

**Comment by pauldambra** [comment]
hey @seawatts 

i appreciate this seems slow to resolve it's unfortunately a pretty fiddly set of changes

it's not possible to run session replay without the canvas recording code at the moment. we are making changes to accommodate this but unfortunately it's such an underlying component that we need to go slowly

**Comment by seawatts** [comment]
Thanks @pauldambra for the prompt response. I'll be submitting my extension without this for now. I'll keep an eye out for changes.

**Comment by nuwansamaware** [comment]
I am using rrweb in my extension: TestChimp: https://chromewebstore.google.com/detail/testchimp-create-api-auto/ailhophdeloancmhdklbbkobcbbnbglm.

How I resolved: After running npx webpack, I manually copy paste the un-encoded code equivalent to the encoded portion.

Attached is the code that needs to be replaced and the replacement code.
[code_to_replace.txt](https://github.com/user-attachments/files/17670521/code_to_replace.txt)
[replacement-code.txt](https://github.com/user-attachments/files/17670522/replacement-code.txt)

**Comment by seawatts** [comment]
Thanks @nuwansamaware That looks like it's a viable solution. However that doesn't seem to be the same code that I'm seeing that is getting obfuscated. My code starts with `KGZ1bmN0aW9uKCkgewogICJ1c2Ugc3RyaWN0IjsKICB2YXIgY2hhcnM`

**Comment by mohammedzamakhan** [comment]
@seawatts have you found the solution for the above code?

**Comment by seawatts** [comment]
No sorry.

**Comment by ruiconti** [comment]
Ran into this, and I believe that I found why this behavior has regressed on `2.0.0-alpha.17`, despite the `rollup.config.js` specifying `preserveSource: true` in `rollup-plugin-web-worker-loader`'s options[^0]:

- `rrweb@2.0.0-alpha.15` has migrated to vite for their bundling tool[^1][^2]
- By doing so, the previous Worker loader specified by `rollup.config.js` is not used anymore.
- Which means that the Worker loader behavior used is `vite@^5.3.1`'s default, which _does_ encode the worker to b64 string by default[^3]
- The above snippet does match what is found in `rrweb@2.0.0-alpha.17`'s bundle present in npm's repository[^4]
- In `vite@^6.0.0`, they've moved away from inlining the base64 source by default, as that has been found to be causing perf hits[^5][^6]
- **Which makes me believe that the fix is simply to bump `vite` to `^6.0.1`, which should produce worker chunks that are 1) more performant and 2) do not cause denied chrome webstore reviews**.

[^0]: https://github.com/rrweb-io/rrweb/blob/83c66c4124a954e8910b1bd880d2a422e5a75f6f/packages/rrweb/rollup.config.js#L151
[^1]: https://github.com/rrweb-io/rrweb/pull/1033
[^2]: https://github.com/rrweb-io/rrweb/pull/1484
[^3]: https://github.com/vitejs/vite/blob/v5.3.6/packages/vite/src/node/plugins/worker.ts#L299-L301
[^4]: https://registry.yarnpkg.com/rrweb-player/-/rrweb-player-2.0.0-alpha.17.tgz
[^5]: https://github.com/vitejs/vite/commit/90c66c95aba3d2edd86637a77adc699f3fd6c1ff
[^6]: https://github.com/vitejs/vite/pull/18752

**Comment by ruiconti** [comment]
I've pushed a fork with a branch confirming that a valid output (i.e., no b64 worker inlined source) by migrating to `vite@^6.0.1`. [#1637](https://github.com/rrweb-io/rrweb/pull/1637)

As remediation for whomever is in need, patching the files that are included in the bundle, replacing the worker loader snippets, seems to be the best path until a fix is merged.

**Comment by pauldambra** [comment]
👋 the vite fix has been validated in prod at posthog for months now (we worked with a devrel at google)

the workaround you link works by disabling session recording... so won't help folk that want to use it 😊

**Comment by featuring-loop** [comment]
I'm using Vite v7.2.2, and the issue above still persists.
Since the rrweb code is bundled inside the Amplitude Session Replay plugin itself, I'm wondering:

Does this need to be updated on the Amplitude side for the fix to take effect?

thks!

**Comment by pauldambra** [comment]
> Does this need to be updated on the Amplitude side for the fix to take effect?

most probably yes
